### ISSUE TITLE
Add Collection to the data_hash keccak::hashv

### ISSUE THREAD

**Issue by c4b4d4** [metaplex-foundation/mpl-bubblegum#64]
Can we change this to take the "collection" in consideration when second-hashing the metadata?

Right now, to verify the collection we need to pass the entire Metadata to the instruction, which reduces composability because it increases the Transaction Size by A LOT.

```
// @dev: seller_fee_basis points is encoded twice so that it can be passed to marketplace
// instructions, without passing the entire, un-hashed MetadataArgs struct
let metadata_args_hash = keccak::hashv(&[message.try_to_vec()?.as_slice()]);
let data_hash = keccak::hashv(&[
    &metadata_args_hash.to_bytes(),
    &message.seller_fee_basis_points.to_le_bytes(),
]);
```
https://github.com/metaplex-foundation/mpl-bubblegum/blob/cea5f00a98778ca4e73694d7b418acd21483c0af/programs/bubblegum/program/src/processor/mint.rs#L113

**Comment by danenbm** [comment]
Thank you for the suggestion and sorry for the much delayed response.  The problem is that the collection verified flag is still part of the Metadata, so even if it were added to the second hashing, if it is changing then the original Metadata must still be provided so that a new first datahash can be validated.  When changing a Metadata field, its imperative that no other fields are inadvertently changed and included in the new datahash.

I think this kind of change would require a new Metadata/leaf schema design, which could be proposed using the MIP process: https://mip.metaplex.com/. However this change I think would be a lot of work and Bubblegum is already pretty integrated into the community.
