### ISSUE TITLE
Bug: Updating the metadata can lead to creator-less cNFTs

### ISSUE THREAD

**Issue by c4b4d4** [metaplex-foundation/mpl-bubblegum#99]
When updating the metadata of a cNFT if none of the creators are verified you can pass an empty Vec and the transaction can go thru. Unless I’m missing something.

There is no check for empty creators Vec when updating the metadata.

https://github.com/metaplex-foundation/mpl-bubblegum/blob/ec267f620e634073acaef85a2d41bcc4f5a039ef/programs/bubblegum/program/src/processor/update_metadata.rs#L143

**Comment by danenbm** [comment]
I think you saw the responses in the dev TG, but just for reference wanted to post it here that it was intentional to allow creatorless cNFTs.  I believe it was considered to broaden the use cases of bubblegum to things like gaming where creators/royalties might not be applicable.  As such it is checked in `assert_metadata_is_mpl_compatible()` and if there are creators, the number of creators must be enforced, no duplicates, and total percentage is 100%.  Empty creator array for Bubblegum is handled in DAS, and it is inconsistent with TM.

I also added some explicit tests for the empty creator array as that is important logic you highlighted: https://github.com/metaplex-foundation/mpl-bubblegum/pull/100
